language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-framer' ]; then cd .. && eval "mv $currentfolder generator-framer" && cd generator-framer; fi

